version: "2.4"

services:
  db:
    image: postgres:15-alpine
    container_name: "postgres_db"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pg_db
      POSTGRES_PORT: 5432
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: "pgadmin"
    environment:
      PGADMIN_DEFAULT_EMAIL: email
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - data_pgadmin:/var/lib/pgadmin
    ports:
      - "8080:80"

volumes:
  postgres_data:
  data_pgadmin:
